<?php

return [
    'company_types' => [
        'Information Technology (IT) Services',
        "Healthcare",
        'Manufacturing',
        'Finance',
        'Retail',
        'Education',
        'Hospitality',
        'Real Estate',
        'Transportation and Logistics',
        'Energy and Utilities',
        'Non-profit and Social Services',
        'Retail and E-commerce',
        'Sports and Recreation',
        'Agriculture and Farming',
        // Food and Beverage
        'Automotive',
        // Media and Entertainment
        'Construction', 
        // Pharmaceuticals
        'Telecommunications',
        'Consulting Services',
        // Aerospace and Defense
        // Biotechnology
        // Fashion and Apparel
        // Government and Public Administration
        'Insurance'
        // Legal Services
        // Marketing and Advertising
        // Mining and Metals
    ],
    'skills' => [
            'Software Development' => [
                'Html',
                'CSS',
                'Boot Strap',
                'Jquery',
                'Word Press',
                'Codeigniter',
                'Express',
                'PHP',
                'JavaScript',
                'Python',
                'Java',
                'C#',
                'Ruby',
                'Go',
                'Swift',
                'C++',
                'Laravel',
                'React',
                'Angular',
                'Vue.js',
                'Spring',
                'Django',
                'Flask',
                'Node.js',
                'Git',
                'GitHub',
                'GitLab',
                'Bitbucket',
                'MySQL',
                'PostgreSQL',
                'MongoDB',
                'SQLite',
                'Oracle',
                'SQL Server',
                'Agile/Scrum',
                'Unit Testing',
                'DevOps',
                'CI/CD',
                'APIs',
                'Microservices',
                'Docker'
            ],
            'Data Science' => [
                'Python',
                'R',
                'SQL',
                'Pandas',
                'NumPy',
                'SciPy',
                'MATLAB',
                'TensorFlow',
                'Keras',
                'Scikit-learn',
                'PyTorch',
                'XGBoost',
                'Tableau',
                'Power BI',
                'Matplotlib',
                'Seaborn',
                'D3.js',
                'Big Data',
                'Hadoop',
                'Spark',
                'Data Cleaning',
                'Data Mining'
            ],
            'Digital Marketing' => [
                'Keyword Research',
                'On-page SEO',
                'Off-page SEO',
                'Technical SEO',
                'Blogging',
                'Copywriting',
                'Content Creation',
                'Content Strategy',
                'Facebook Marketing',
                'Instagram Marketing',
                'LinkedIn Marketing',
                'Twitter Marketing',
                'TikTok Marketing',
                'Mailchimp',
                'Constant Contact',
                'A/B Testing',
                'Campaign Optimization',
                'Google Analytics',
                'Google Ads',
                'PPC',
                'Affiliate Marketing',
                'Conversion Rate Optimization (CRO)'
            ],
            'Project Management' => [
                'Agile',
                'Scrum',
                'Kanban',
                'Waterfall',
                'Lean',
                'Jira',
                'Trello',
                'Asana',
                'Microsoft Project',
                'Basecamp',
                'Risk Management',
                'Time Management',
                'Resource Management',
                'Budgeting',
                'Team Leadership',
                'Stakeholder Management',
                'Communication',
                'Problem-Solving',
                'Critical Thinking'
            ],
            'Graphic Design' => [
                'Adobe Photoshop',
                'Adobe Illustrator',
                'Adobe InDesign',
                'CorelDRAW',
                'Sketch',
                'Typography',
                'Layout Design',
                'Branding',
                'Logo Design',
                'Illustration',
                'Figma',
                'Canva',
                'InVision',
                'Adobe XD',
                'Creative Thinking',
                'Attention to Detail',
                'Color Theory',
                'Visual Communication'
            ],
            'Human Resources' => [
                'Job Posting',
                'Screening',
                'Interviewing',
                'Onboarding',
                'Conflict Resolution',
                'Performance Management',
                'Employee Engagement',
                'Employment Laws',
                'Labor Relations',
                'Diversity and Inclusion',
                'HRIS Systems',
                'Applicant Tracking Systems',
                'Payroll Software',
                'Training and Development',
                'Organizational Development',
                'Compensation and Benefits'
            ],
            'Sales' => [
                'Cold Calling',
                'Lead Generation',
                'Account Management',
                'Negotiation',
                'Salesforce',
                'HubSpot',
                'Zoho CRM',
                'Pipedrive',
                'Customer Relationship Management',
                'Product Knowledge',
                'Communication',
                'Sales Presentation',
                'Market Research',
                'Sales Forecasting',
                'Networking',
                'Closing Techniques'
            ],
            'Customer Service' => [
                'Phone Support',
                'Email Support',
                'Live Chat',
                'Social Media Support',
                'Communication',
                'Problem-Solving',
                'Empathy',
                'Active Listening',
                'Conflict Resolution',
                'Zendesk',
                'Freshdesk',
                'Salesforce Service Cloud',
                'Intercom',
                'Customer Satisfaction',
                'Customer Retention',
                'Feedback Collection',
                'Technical Support'
            ],
            'Accounting and Finance' => [
                'QuickBooks',
                'Xero',
                'SAP',
                'Oracle Financials',
                'Financial Analysis',
                'Budgeting',
                'Tax Preparation',
                'Auditing',
                'Bookkeeping',
                'Payroll Management',
                'Accounts Payable',
                'Accounts Receivable',
                'Financial Reporting'
            ],
            'Healthcare' => [
                'Patient Care',
                'Medical Terminology',
                'EMR/EHR Systems',
                'Clinical Procedures',
                'Diagnostics',
                'Epic Systems',
                'Cerner',
                'Meditech',
                'Allscripts',
                'CPR',
                'BLS',
                'ACLS',
                'PALS',
                'Communication',
                'Teamwork',
                'Attention to Detail',
                'Compassion'
            ],        
    ]
];
